feat(charts): add OpeningsBarChat
achilio/lichess-visualizator pull request #6
Opened 2023-01-28 23:55 UTC by estebgonza

<img width="430" alt="6612b88084c2384ab6ec37e1c0c78fff" src="https://user-images.githubusercontent.com/32603471/215296505-90bfc3ed-9fc0-4cec-a3c5-ffbccebffe87.png">

2023-01-29 00:04 UTC, NicoGGG commented on src/components/HomePage.vue
> +        <WinrateKpi />
On utilise pas la notation officiel ? winrate-kpi et openings-bar-chart ?

2023-01-29 08:45 UTC, NicoGGG commented on src/components/WinrateKpi.vue
> +  height: 100%;
Ça sert a quoi ?

2023-01-29 08:51 UTC, NicoGGG requested changes
Y'a des soucis avec le bar chart.
- Le titre c'est X
- C'est trop petit en hauteur, on ne voit pas la légende de la 2è bar
- Il faudrait un tooltip quand on hover une bar

Bon et au niveau des dimensions je suis pas trop convaincu de set ça dans le grid. Ou pas uniquement en tout cas

2023-01-29 10:08 UTC, NicoGGG commented on src/components/OpeningsBarChart.vue
> +)
Ça prend le premier move de la game là mais c'est pas forcément le premier move du player du coup

2023-02-02 08:37 UTC, estebgonza commented on src/components/OpeningsBarChart.vue
> +)
Mais oui ! Bien vu :-)

2023-02-02 16:45 UTC, NicoGGG approved these changes

2023-02-02 16:48 UTC, merged